# Default configuration
#   org: default organization for components
[default]
org = "ssh://git@github.com/shilei-massclouds"

# Functional components list
# Style 1 - short path
#   component-name = "repo-name"
# It means: component is in the repo ("default.org/repo-name")
#
# Style 2 - full path
#   component-name = "full-repo-url"
# E.g., foo = "ssh://git@github.com/org_foo/repo_foo"
[mod_list]
arch_boot = "arch_boot"
axconfig = "axconfig"
mm = "mm"
axdriver = "axdriver"
memory_addr = "memory_addr"
#hal_base = "hal_base"
axhal = "axhal"
#earlycon = "earlycon"
early_console = "early_console"
#ramdisk = "ramdisk"
driver_block = "driver_block"
driver_virtio = "driver_virtio"
driver_pci = "driver_pci"
driver_common = "driver_common"
axerrno = "axerrno"
axtype = "axtype"
#axlog = "axlog"
axlog2 = "axlog2"
spinbase = "spinbase"
axalloc = "axalloc"
allocator = "allocator"
#kernel_guard = "kernel_guard"
kernel_guard_base = "kernel_guard_base"
mutex = "mutex"
taskctx = "taskctx"
task = "task"
wait_queue = "wait_queue"
run_queue = "run_queue"
scheduler = "scheduler"
#percpu = "percpu"
percpu2 = "percpu2"
percpu_macros2 = "percpu2"
page_table = "page_table"
page_table_entry = "page_table"
lazy_init = "lazy_init"
ratio = "ratio"
axmount = "axmount"
fstree = "fstree"
axfile = "axfile"
axio = "axio"
capability = "capability"
filetable = "filetable"
axdtb = "axdtb"
axtrap = "axtrap"
exec = "exec"
axsyscall = "axsyscall"
fileops = "fileops"
mmap = "mmap"
sys = "sys"
signal = "signal"
handler_table = "handler_table"
elf = "elf"
fork = "fork"
userboot = "userboot"

# Root components list
# Styles are just as [mod_list]
[root_list]
rt_axconfig = "axconfig"
rt_early_console = "early_console"
rt_axlog2 = "axlog2"
rt_axhal = "axhal"
rt_user_stack = "user_stack"
rt_driver_block = "driver_block"
rt_driver_virtio = "driver_virtio"
rt_axmount = "axmount"
rt_mutex = "mutex"
rt_axalloc = "axalloc"
rt_page_table = "page_table"
rt_pflash = "pflash"
rt_bprm_loader = "bprm_loader"
rt_mm = "mm"
rt_fstree = "fstree"
#rt_task = "task"
rt_mmap = "mmap"
rt_run_queue = "run_queue"
rt_fileops = "fileops"
rt_fork = "fork"
rt_exec = "exec"
#rt_axtrap = "axtrap"
rt_macrokernel = "macrokernel"
#test_axmount = "axmount"

rt_tour_0_1 = "tour_stage"

rt_tour_1_1 = "tour_stage"
rt_tour_1_2 = "tour_stage"
rt_tour_1_3 = "tour_stage"
rt_tour_1_4 = "tour_stage"
rt_tour_1_5 = "tour_stage"
rt_tour_1_6 = "tour_stage"

rt_tour_2_1 = "tour_stage"
rt_tour_2_2 = "tour_stage"
rt_tour_2_3 = "tour_stage"
rt_tour_2_4 = "tour_stage"
rt_tour_2_5 = "tour_stage"
rt_tour_2_6 = "tour_stage"

rt_tour_3_1 = "tour_stage"
rt_tour_3_2 = "tour_stage"
rt_tour_3_3 = "tour_stage"
rt_tour_3_4 = "tour_stage"

rt_tour_4_1 = "tour_stage"
