[package]
name = "fstree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
axhal = { git = "ssh://git@github.com/shilei-massclouds/axhal" }
axfs_vfs = { git = "ssh://git@github.com/shilei-massclouds/axfs_vfs.git" }
axerrno = { git = "ssh://git@github.com/shilei-massclouds/axerrno.git" }
spinpreempt = { git = "ssh://git@github.com/shilei-massclouds/spinpreempt.git" }
axalloc = { git = "ssh://git@github.com/shilei-massclouds/axalloc" }
page_table = { git = "ssh://git@github.com/shilei-massclouds/page_table" }
axdriver = { git = "ssh://git@github.com/shilei-massclouds/axdriver" }
axmount = { git = "ssh://git@github.com/shilei-massclouds/axmount" }
