[package]
name = "rt_tour_0_1"
version = "0.1.0"
edition = "2021"

[dependencies]
arch_boot = { git = "ssh://git@github.com/shilei-massclouds/arch_boot.git" }
axhal = { git = "ssh://git@github.com/shilei-massclouds/axhal" }
