[package]
name = "signal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
cfg-if = "1.0"
taskctx = { git = "ssh://git@github.com/shilei-massclouds/taskctx.git" }
task = { git = "ssh://git@github.com/shilei-massclouds/task.git" }
axhal = { git = "ssh://git@github.com/shilei-massclouds/axhal.git" }
axtype = { git = "ssh://git@github.com/shilei-massclouds/axtype.git" }
axerrno = { git = "ssh://git@github.com/shilei-massclouds/axerrno.git" }
